notify:
  name: 通知
  description: 发送消息通知到家庭助理TV应用
  fields:
    message:
      name: Message
      description: 消息内容
      required: true
      example: 消息内容
      selector:
        text:
    title:
      name: Title
      description: 标题
      required: true
      example: 标题
      selector:
        text: